"""manual.py — per-page contextual help snippets.

Used by the ``help_expander(page_id)`` helper to drop a *Help on this page*
expander on the main workflow pages. Keeps copy in one place so the Help
page index and the per-page hints stay in sync.
"""
from __future__ import annotations

import streamlit as st


_HELP: dict[str, str] = {
    "home": (
        "**SHARC-Orbit**\n\n"
        "Landing page. The sidebar is the menu.\n\n"
        "* **Input** — **Upload** registers an SRS filing and its PFD "
        "mask. **Uploads** lists what was registered.\n"
        "* **Inspect** — **Mask viewer** draws one PFD mask. "
        "**Constellation** draws the non-GSO satellites of a filing. "
        "Neither launches a run.\n"
        "* **Examine** — **Single-entry** runs ITU-R S.1503-4 on one "
        "system. **Aggregate** combines two or more. **National "
        "occupancy** surveys which bands are taken; it does not run "
        "EPFD and it does not download catalogues.\n"
        "* **Runs & results** — **Runs** is the history, **Status** the "
        "live log, **Results** the CCDF.\n"
        "* **Cluster** is optional, and only useful with more than one "
        "machine.\n\n"
        "Files stay on this machine. The app does not fetch an SRS, a "
        "mask, or a licensed-station table for you."
    ),
    "upload": (
        "**Upload page**\n\n"
        "Register an SRS filing. Two stages:\n\n"
        "1. **Files** — the SRS `.mdb` and the PFD mask `.mdb` are both "
        "required. Operating-parameter masks (`.xml`) are optional: "
        "upload them only when the mask database does not already carry "
        "the S.1503-4 §B3.3 parameters (MIN_EXCLUDE, MIN_ELEV, "
        "MAX_CO_FREQ, MIN_DURATION). Give the filing a label. Files are "
        "copied into `streamlit_app/data/uploads/<id>/`.\n"
        "2. **Notices** — the page lists every notice (`ntc_id`) and the "
        "PFD masks it found. Tick the notices to register. Each notice "
        "becomes one **system**, pickable on Uploads, Single-entry and "
        "Aggregate. You do not pick a mask per notice: when several PFD "
        "masks are linked by `mask_lnk1`, the engine distributes them "
        "across the satellites.\n\n"
        "One MDB can hold several notices. Register any subset.\n\n"
        "The Step-2 label is suggested from the satellite name, the "
        "**filing-name prefix** set on Uploads, and a timestamp. You can "
        "edit it before registering."
    ),
    "uploads": (
        "**Uploads page**\n\n"
        "Every registered filing and system.\n\n"
        "* **Filing name prefix** — **Apply** renames every existing "
        "filing and becomes the default prefix for new uploads.\n"
        "* **Maintenance** — delete selected filings, or all of them. "
        "Deleting a filing cascades its systems. Run artifacts are "
        "removed from the **Runs** page.\n"
        "* **Orbital parameters** — planes, satellites per plane, "
        "semi-major axis, altitude, perigee, apogee, eccentricity, "
        "inclination, RAAN, argument of perigee, period, precession, "
        "sun-synch and station-keeping, read from the SRS `orbit` "
        "table. The system picker here is shared with Single-entry, "
        "Aggregate, Mask viewer and Constellation.\n"
        "* **Operating frequency bands** — masks (`mask_info`) with PFD "
        "/ EIRP / Other, and groups (`grp`) with Tx/Rx, beam and minimum "
        "elevation.\n"
        "* **View mask** — opens that PFD mask in **Mask viewer**.\n\n"
        "The lower section re-scans a filing for notices or deletes that "
        "filing."
    ),
    "single_entry": (
        "**Single-entry page (ITU-R S.1503-4)**\n\n"
        "Full single-system pipeline on **one** system.\n\n"
        "**1. System.** The picker is shared with the other Examine and "
        "Inspect pages. The band chart shows SRS emission (Tx), "
        "reception (Rx) and PFD-mask bands. An **Article 22** scenario, "
        "when you pick one, sets service, earth-station antenna, "
        "reference bandwidth and the run frequency; left on Auto, the "
        "engine resolves them from the band. A filing that declares "
        "several configurations (`multi_config_type = M`) can launch the "
        "registered sibling databases with the same parameters.\n\n"
        "**2. Geometry.**\n\n"
        "1. **S.1503-4 WCGA** — §D.3.1: latitude sweep, (θ, φ) grid, "
        "binary search on the α₀ / ε₀ boundaries, then EPFD↓ at the "
        "worst-case geometry. One or more countries restrict the "
        "earth-station domain (**territorial WCGA**) and enable the "
        "RAAN (Ω) sweep (auto per orbit, §D4.6.1). Empty country list "
        "= world-wide.\n"
        "2. **Defined geometry** — skip the WCGA; EPFD↓ at one "
        "earth-station / GSO coordinate.\n"
        "3. **ES×GSO grid (no WCGA)** — the same grid as Aggregate "
        "method 2 on this filing. Headline CCDF is the worst-per-"
        "percentile envelope. Optional country filter. MIN_DURATION is "
        "applied per earth-station latitude (§D5.1.4.2), with that "
        "latitude's MAX_CO_FREQ, α₀ and ε₀.\n\n"
        "**3. Simulation parameters.** Empty fields use the engine "
        "default. Compliance is the CCDF against Article 22 §22.5.\n\n"
        "Collapsed sections cover the WCG search (`s1503_step`, "
        "`gso_longitude_mode`, `alpha_method`), the defined point, the "
        "§D.4.7 dual time step, and **Orbital dynamics** — station "
        "keeping (`Wdelta`), artificial precession, and precession taken "
        "from the SRS (§D6.3)."
    ),
    "country_single_entry": (
        "**Territorial WCGA** now lives on **Single-entry**.\n\n"
        "Pick **Geometry → S.1503-4 WCGA** and select one or more "
        "countries. Empty selection = world-wide §D.3.1 WCGA. "
        "Non-empty = territorial ES domain + RAAN (Ω) sweep."
    ),
    "aggregate": (
        "**Aggregate page (Resolution 76 studies)**\n\n"
        "Combines **two or more** systems.\n\n"
        "**1. Systems.** The band chart shows whether the selection is "
        "co-channel before you launch. An **Article 22** scenario, when "
        "the filings share one, sets the service and the earth-station "
        "antenna for every system in the run.\n\n"
        "**2. Aggregation method.** Four methods. Each radio item states "
        "its strategy and cost; the panel under the radio is the "
        "step-by-step for the one you picked.\n\n"
        "* `method_1` — convolve each filing's CCDF at its own "
        "worst-case geometry.\n"
        "* `method_2` — sweep an earth-station × GSO grid; the headline "
        "is the envelope.\n"
        "* `method_3` — one joint simulation of the combined "
        "constellation.\n"
        "* `method_4` — at each filing's worst-case geometry, simulate "
        "every system. Audit of how much the choice of geometry matters.\n\n"
        "The comparison is on the **Help** page.\n\n"
        "**3. Simulation parameters.** Empty N and Δt are resolved "
        "**per filing**, the same way as an independent Single-entry of "
        "that system. WCG search, time step and **Orbital dynamics** "
        "(station keeping, precession) apply per filing.\n\n"
        "**Convolution tail (S.1588 Annex 1 §1)** sits after Orbital "
        "dynamics. The tail floor is used only when its checkbox is "
        "ticked, and only by the convolving methods. Reloading a run "
        "from **Runs** restores the truncation settings."
    ),
    "launcher": (
        "**Launcher page (campaign mode)**\n\n"
        "Launches **multiple methods on the same set of systems** as a "
        "single campaign. Useful when you want to compare aggregation "
        "approaches under identical inputs.\n\n"
        "Mirrors **every Aggregate option** — WCG search, time step, "
        "**Orbital dynamics** (station keeping / precession) and the "
        "method-2 grid params (grid / GSO step, max geometries, country "
        "filter). Set once → applied to all selected methods. The form is "
        "**persisted** across visits (same defaults as Aggregate).\n\n"
        "All child runs share a `campaign_id` and roll up in the "
        "**Campaign** dashboard (with XLSX export)."
    ),
    "runs": (
        "**Runs page**\n\n"
        "Local history of every run (DB-synced). Each row's **actions** "
        "column has four shortcut buttons:\n\n"
        "- :material/insights: → open **Results** for that run.\n"
        "- :material/pending: → open **Status** for that run.\n"
        "- :material/settings_backup_restore: → **reload this study's "
        "config** into the matching form (Single-entry / Aggregate), "
        "pre-filled, so you can re-run with the same settings. Warns if "
        "the original filing was deleted.\n"
        "- :material/delete: → **delete** that run + its artifacts "
        "(asks to confirm).\n\n"
        "Click the `id` button to pre-select the run in *Inspect / "
        "delete* below. The **Maintenance** toolbar at the top bulk-"
        "deletes runs by status — failed / cancelled / success — or "
        "**ALL runs** (also confirmed)."
    ),
    "status": (
        "**Status page**\n\n"
        "Live worker log + progress bar. The fragment polls every 2 s "
        "and prints the raw engine output (Numba progress bars are "
        "split on `\\r` so they don't pile up into one giant line).\n\n"
        "While the run is active it also shows **host CPU%/memory** and, "
        "when distributed, **per-worker** utilisation (probed ~10 s). "
        "Probing stops once the run finishes. Tail / log font size are "
        "persisted in session state."
    ),
    "results": (
        "**Results page**\n\n"
        "- **CCDF chart** — the headline curve, plus per-WCG overlays "
        "(method 4) or per-(point, system) overlays (method 2). Article "
        "22 and Resolution 76 limits are drawn dashed and dotted.\n"
        "- **Normative percentiles** — bars at the Resolution 76 time "
        "percentages. With S.1588 convolution-tail truncation on, "
        "percentiles below the floor read **n/a (below truncation "
        "floor)**.\n"
        "- **Temporal sampling** — the §D4 / §D4.7 dual time step "
        "actually used (fine, coarse, and how many of each ran).\n"
        "- **Track duration** — sliding windows when the run used "
        "S.1503-4 §D5.1.4.2 (MIN_DURATION ≠ 0).\n"
        "- **Globe** — earth station, GSO and grid markers. Click a "
        "point to select it in the geometry picker; **Show CCDF** opens "
        "that point's curve with the limit overlays.\n"
        "- **EPFD time series** — the downlink trace. On a joint run "
        "this is per system at the joint worst-case geometry; on "
        "single-entry it is the one system's trace.\n"
        "- **Compare external MDB(s)** — upload SHARC results `.mdb` "
        "files to overlay their reference CCDF (table `cdf`)."
    ),
    "campaign": (
        "**Campaign page**\n\n"
        "Aggregated view of every run sharing the selected `campaign_id`. "
        "Lists each child run with status/progress, then exports a "
        "multi-sheet XLSX (`campaign`, `runs`, `params`) capturing the "
        "campaign for archival."
    ),
    "mask_viewer": (
        "**Mask viewer**\n\n"
        "Interactive view of one ITU-R S.1503-4 PFD mask. No run is "
        "required.\n\n"
        "* Open it from **Uploads** → *View mask*, from **Constellation** "
        "after projecting a footprint, or pick the mask on this page. "
        "The last mask follows you across pages.\n"
        "* Header: mask id, type, shape, PFD range in dBW/m².\n"
        "* The A and B sliders are **degrees**, not cell indices.\n"
        "* The heatmap is *Uniform* (equal-width cells) or "
        "*Proportional* (real degrees on the axis). A slice plot shows "
        "PFD along the C axis at the selected cell.\n"
        "* The calculator returns PFD at any `(a, b, c)` in degrees, "
        "with the same interpolation the engine uses at runtime.\n\n"
        "Only PFD masks (`f_mask = P`) render. EIRP and Other masks are "
        "listed on Uploads and are not drawn here. Conversion between "
        "alpha and azimuth/elevation is not in this page."
    ),
    "constellation": (
        "**Constellation**\n\n"
        "3D globe of one registered non-GSO filing, at t = 0. No run is "
        "required. A GSO-only filing, or a mask database registered as "
        "the SRS, has nothing to draw.\n\n"
        "* **Scenario** — an Article 22 downlink case with the "
        "earth-station antenna diameter collapsed, because the diameter "
        "does not change which satellites transmit. Each scenario is "
        "service × band × reference bandwidth × table. **Complete** "
        "shows every satellite, at every frequency.\n"
        "* **Filter** — *Emitters only* keeps satellites that radiate in "
        "that scenario's band (`grp` joined to `mask_lnk1`). *All* keeps "
        "the rest, dimmed.\n"
        "* **Color** — by emitter (yellow / grey) or by orbital plane.\n"
        "* Click a satellite, or pick it in the list, then **Project "
        "mask**. The page isolates that satellite and draws its PFD mask "
        "as a footprint. **Open in Mask viewer** continues in the 2D "
        "viewer.\n\n"
        "Metrics under the scenario are total satellites, emitters, "
        "planes, altitude, inclination and eccentricity."
    ),
    "cluster": (
        "**Cluster page (optional)**\n\n"
        "Configure Ray distributed processing. **Standalone** already "
        "saturates this machine's cores (WCGA + EPFD pools). Switch to "
        "**Ray cluster** to spread across machines — both the aggregate "
        "sub-simulations AND the interior of a single heavy run (WCGA "
        "latitude sweep + EPFD time-chunks) fan out.\n\n"
        "When the head runs on this host the driver connects natively "
        "(GCS address), not the fragile `ray://` client. Attach workers "
        "with `ray start --address=<HEAD>:6379`. See the Help page for "
        "the multi-host walk-through."
    ),
    "national_occupancy": (
        "**National band occupancy**\n\n"
        "Survey of which bands are occupied. It does not launch an EPFD "
        "run, and it does not download anything.\n\n"
        "**1. Catalogs.** Three ways in, all optional and all local:\n\n"
        "* **National licensed catalogue** — your administration's "
        "stations, one table per catalogue. The shape is **Licensed-"
        "station table format** below. Give it the licensing "
        "administration's **ITU symbol** (not an ISO code) so the "
        "country filter can find the rows. The page works with none of "
        "these; it then shows filings only.\n"
        "* **ITU filings** — the complete SRS. Paste a path on this "
        "machine: a BR IFIC ISO, the ITU bookshop zip, `srsNNNN.zip`, a "
        "folder of the split `.mdb` parts, or one `.mdb`. The page "
        "extracts `SRS.mdb` from an ISO with `xorriso` and indexes every "
        "notice. The weekly `ificXXXX.mdb` is not a source: it only has "
        "that week's publications.\n"
        "* **Add another filing catalogue** — a second SRS (another "
        "IFIC, another administration, a filing of your own), indexed "
        "**beside** the one already loaded. It does not replace it.\n\n"
        "The **country is a filter** over an index, so you can change it "
        "without re-indexing. Each notice carries its notifying "
        "administration, its service area and the countries of its earth "
        "stations. **Serves it** counts a filing that was notified by "
        "the administration, that lists the country (or its ITU Region "
        "`XR1`/`XR2`/`XR3`, or worldwide `XAA`) in the service area, or "
        "that has an earth station there. **Notified by it** keeps only "
        "the notifying administration. Symbols are the ITU's: `B` "
        "Brazil, `F` France, `D` Germany, `G` the United Kingdom.\n\n"
        "**2. Systems.** Filter by source, orbit, direction, letter "
        "band, a GHz window and a name. Pick the rows to draw.\n\n"
        "**3. Occupied bands.** The same shared-axis strips as "
        "Aggregate, plus the **common overlap** (bands taken by every "
        "selected system). The line under a name is the letter bands of "
        "that bar, and the operator when the source names one. "
        "Direction **Both** merges uplink and downlink before "
        "intersecting, so a reported overlap may pair one system's "
        "uplink with another's downlink.\n\n"
        "**4. Assignments.** One row per sub-band, with position, "
        "operator and the numeric edges, exportable as CSV."
    ),
    "national_catalog_format": (
        "**Licensed-station table format**\n\n"
        "One CSV, or a zip containing it. **One row per station per "
        "sub-band**, not one row per station: a station with four sub-bands "
        "has four rows, and the page merges them.\n\n"
        "| Column | Meaning | Required | Example |\n"
        "| --- | --- | --- | --- |\n"
        "| station | Name of the licensed space station. Rows sharing a name "
        "become one system. | **yes** | `STARONE C3` |\n"
        "| freq_min_mhz | Lower edge of the sub-band, **in MHz**. | **yes** | "
        "`10700` |\n"
        "| freq_max_mhz | Upper edge of the sub-band, in MHz. | **yes** | "
        "`11700` |\n"
        "| direction | Which way the sub-band goes. | no, but without it "
        "every row counts as downlink | `downlink` / `uplink` |\n"
        "| operator | Licensee. Shown under the station name on the "
        "chart when present. | no | `EMBRATEL` |\n"
        "| orbit | `GEO` or `NGEO`; drives the Orbit filter. | no | `GEO` |\n"
        "| orbital_position | Longitude or slot. Kept on the system and "
        "shown in the Assignments table, not under the chart name. | no | "
        "`70W` |\n"
        "| rf_band | The administration's own band label. | no | `Ku` |\n"
        "| station_id | Licence or station number. | no | `1234` |\n"
        "| valid_until | Licence validity, carried as provenance. | no | "
        "`2030-12-31` |\n\n"
        "**Details that bite.**\n\n"
        "* **Column names** may be in English as above, or the Portuguese "
        "names of the reference open-data table (`NomeEstacao_STEL_portal`, "
        "`MedFrequenciaInicialMHz_STEL_portal`, `Sentido_STEL_portal`, …). "
        "Matching is case-insensitive and also accepts a name that merely "
        "contains the one listed.\n"
        "* **Frequencies are MHz.** A file in GHz parses without complaint and "
        "draws bands a thousand times too narrow; the page checks the range "
        "and refuses a file whose highest frequency is under 1 000.\n"
        "* **Decimal separator** may be a dot or a comma: `1635,725` and "
        "`1635.725` are both read as 1 635.725 MHz.\n"
        "* **Delimiter** is detected, semicolon or comma. **Encoding** may be "
        "UTF-8 (with or without BOM), CP1252 or Latin-1.\n"
        "* **Direction** is matched by word, not by language: `subida` / "
        "`uplink` / `Earth-to-space` / `E-S` / `ascendente` all mean uplink, "
        "and the descending equivalents mean downlink. A word in neither list "
        "is filed as downlink and reported, so a column the page did not "
        "understand is visible rather than silent.\n"
        "* Columns the page does not use are ignored, so an export with extra "
        "fields is fine."
    ),
}


def help_expander(page_id: str, *, label: str = "Help on this page",
                  extra: "tuple[str, ...] | None" = None) -> None:
    """Drop a collapsed expander on the page with its contextual snippet.

    ``extra`` names further ``_HELP`` entries to fold in under the first, each
    in its own nested expander — for reference material a page needs at hand
    but should not open with, such as an input-file contract.

    Silently no-op when ``page_id`` is unknown; unknown ``extra`` keys are
    skipped the same way.
    """
    text = _HELP.get(page_id)
    if not text:
        return
    with st.expander(label, expanded=False, icon=":material/help_outline:"):
        st.markdown(text)
        for key in (extra or ()):
            body = _HELP.get(key)
            if not body:
                continue
            title = body.lstrip().split("\n", 1)[0].strip("* ")
            with st.expander(title, expanded=False):
                st.markdown(body)
        st.page_link(
            "pages/A_Help.py",
            label="Open full manual",
            icon=":material/menu_book:",
        )
