"""Translate a Streamlit-style params JSON/YAML into a src.main CLI invocation.

Reads a params file (JSON or commented-JSON/YAML as generated by the Streamlit
UI), maps every parameter to the corresponding src.main CLI flag, and either
prints the resulting command or executes it directly.

Parameters that have no CLI flag (alpha_method, gso_longitude_mode,
apply_station_keeping, wcga_no_mask_symmetry, restrict_emitters_to_sim_band)
are written to a temporary config.yaml in the repo root, which src.main merges
automatically on startup, and cleaned up when the run finishes.

Usage:
    python -m src.run_from_params input/params.json
    python -m src.run_from_params input/params.json --run
    python -m src.run_from_params input/params.json --run --output results/
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path


# ── Params loader ──────────────────────────────────────────────────────────────

def _load_params(path: str) -> dict:
    text = Path(path).read_text(encoding="utf-8")
    # Strip # comments and trailing commas so the Streamlit-generated
    # commented-JSON is accepted by the standard JSON parser.
    text = re.sub(r"^\s*#[^\n]*$", "", text, flags=re.MULTILINE)
    text = re.sub(r",(\s*[}\]])", r"\1", text)
    return json.loads(text)


# ── Mapping ────────────────────────────────────────────────────────────────────

def build_argv(params: dict) -> tuple[list[str], dict, list[str]]:
    """Return (argv, config_overrides, warnings).

    argv            -- flags to append after ``python -m src.main``
    config_overrides -- sections to write into a temporary config.yaml for
                        params that have no CLI counterpart
    warnings        -- human-readable notes about unmapped or ignored params
    """
    argv: list[str] = []
    config_overrides: dict = {}
    warnings: list[str] = []

    # ── File paths ─────────────────────────────────────────────────────────────
    srs_path = params.get("srs_path")
    mask_path = params.get("mask_path") or params.get("pfd_mask_path")

    if not srs_path:
        raise ValueError("params file is missing 'srs_path'")
    argv += ["--mdb", srs_path]

    if mask_path:
        if str(mask_path).lower().endswith(".xml"):
            argv += ["--pfd-xml", mask_path]
        else:
            argv += ["--pfd-mask-mdb", mask_path]
    else:
        warnings.append(
            "No mask_path/pfd_mask_path found; mask will be auto-detected from the SRS MDB."
        )

    if params.get("mask_id") is not None:
        argv += ["--mask-id", str(int(params["mask_id"]))]

    if params.get("ntc_id"):
        argv += ["--ntc-id", str(params["ntc_id"])]

    if params.get("service"):
        argv += ["--service", params["service"]]

    # ── Earth station ──────────────────────────────────────────────────────────
    if params.get("es_antenna_diameter_m") is not None:
        argv += ["--es-antenna-diameter", str(params["es_antenna_diameter_m"])]

    if params.get("reference_bandwidth_khz") is not None:
        argv += ["--reference-bandwidth-khz", str(params["reference_bandwidth_khz"])]

    # ── Time steps ─────────────────────────────────────────────────────────────
    if params.get("num_time_steps") is not None:
        argv += ["--nsteps", str(int(params["num_time_steps"]))]

    if params.get("time_step_s") is not None:
        argv += ["--coarse-time-step-s", str(params["time_step_s"])]

    if params.get("fine_time_step_s") is not None:
        argv += ["--fine-time-step-s", str(params["fine_time_step_s"])]

    dual = params.get("dual_time_step_mode")
    if dual is not None:
        # "on" is the UI shorthand for the normative S.1503 rule
        mapped = "s1503" if dual == "on" else dual
        if mapped in ("s1503", "alpha_threshold", "off"):
            argv += ["--dual-time-step-mode", mapped]

    # ── WCGA ───────────────────────────────────────────────────────────────────
    if params.get("wcga_s1503"):
        argv.append("--wcga-s1503")

    if params.get("s1503_step_deg") is not None:
        argv += ["--s1503-step", str(params["s1503_step_deg"])]

    if params.get("s1503_trail_all_points"):
        argv.append("--s1503-trail-all-points")

    if params.get("wcga_flat_threshold"):
        argv.append("--wcga-flat-threshold")

    if params.get("wcg_manual"):
        argv.append("--wcg-manual")
        for key, flag in [
            ("wcg_manual_es_lat",  "--wcg-manual-es-lat"),
            ("wcg_manual_es_lon",  "--wcg-manual-es-lon"),
            ("wcg_manual_gso_lon", "--wcg-manual-gso-lon"),
        ]:
            if params.get(key) is not None:
                argv += [flag, str(params[key])]

    # ── Orbital dynamics ───────────────────────────────────────────────────────
    if params.get("artificial_precession"):
        argv.append("--artificial-precession")

    if params.get("use_precession_mdb"):
        argv.append("--use-precession-mdb")

    # ── Misc ───────────────────────────────────────────────────────────────────
    if params.get("keep_full_history"):
        argv.append("--keep-full-history")

    # run_static_es defaults to False in the worker; --no-static-es disables it
    # in the CLI (which defaults to running it). Only suppress when explicitly false.
    if params.get("run_static_es") is False:
        argv.append("--no-static-es")

    # ── Params without CLI flags → config.yaml overrides ──────────────────────
    sim: dict = {}
    wcg: dict = {}

    alpha = params.get("alpha_method")
    if alpha and alpha != "sweep":  # "sweep" is the engine default
        sim["alpha_method"] = alpha

    glo = params.get("gso_longitude_mode")
    if glo and glo != "arc_optimal":  # "arc_optimal" is the engine default
        sim["gso_longitude_mode"] = glo

    if params.get("apply_station_keeping"):
        sim["apply_station_keeping_wdelta"] = True

    if params.get("restrict_emitters_to_sim_band"):
        sim["restrict_emitters_to_sim_band"] = True

    if params.get("wcga_no_mask_symmetry"):
        wcg["s1503_symmetric_mask"] = False

    if sim:
        config_overrides["simulation"] = sim
    if wcg:
        config_overrides["wcg_search"] = wcg

    # ── Gap warnings ───────────────────────────────────────────────────────────
    if params.get("min_elevation_deg") is not None:
        warnings.append(
            f"min_elevation_deg={params['min_elevation_deg']} has no CLI flag and "
            "'non_gso' is not in the config.yaml merge list; the value from the "
            "SRS group (elev_min_deg) will be used instead."
        )

    if params.get("simulation_frequency_ghz") is not None:
        warnings.append(
            f"simulation_frequency_ghz={params['simulation_frequency_ghz']} has no "
            "CLI flag and 'pfd_mask' is not in the config.yaml merge list; the "
            "frequency will be auto-resolved from the PFD mask."
        )

    # Reference-vector satellite selection (US proposal R23-WP4A-C-0519).
    # Hold duration comes solely from MIN_DURATION (§D5.1.4.2) — no separate
    # track-duration flag; see
    # artifacts/WP4A_519_track_duration_consolidation_decision.md.
    if params.get("ref_vec_selection"):
        argv.append("--ref-vec-selection")
        if params.get("ref_vec_az_deg") is not None:
            argv += ["--ref-vec-az-deg", str(float(params["ref_vec_az_deg"]))]
        if params.get("ref_vec_el_deg") is not None:
            argv += ["--ref-vec-el-deg", str(float(params["ref_vec_el_deg"]))]
        if params.get("ref_vec_time_window_P_pct") is not None:
            argv += ["--ref-vec-time-window-pct", str(float(params["ref_vec_time_window_P_pct"]))]

    _ui_only = {"srs_relpath", "mask_relpath", "result_path", "system_id"}
    for k in _ui_only:
        if k in params:
            warnings.append(f"Skipped UI-only param: {k!r}")

    return argv, config_overrides, warnings


# ── config.yaml helper ─────────────────────────────────────────────────────────

def _dict_to_yaml(d: dict, indent: int = 0) -> str:
    lines = []
    pad = "  " * indent
    for k, v in d.items():
        if isinstance(v, dict):
            lines.append(f"{pad}{k}:")
            lines.append(_dict_to_yaml(v, indent + 1))
        elif isinstance(v, bool):
            lines.append(f"{pad}{k}: {'true' if v else 'false'}")
        elif isinstance(v, str):
            lines.append(f"{pad}{k}: {v}")
        else:
            lines.append(f"{pad}{k}: {v}")
    return "\n".join(lines)


# ── Entry point ────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Translate a Streamlit params JSON into a src.main CLI invocation."
    )
    parser.add_argument("params_file", help="Path to the params JSON/YAML file.")
    parser.add_argument(
        "--run", action="store_true",
        help="Execute the command instead of just printing it.",
    )
    parser.add_argument(
        "--output", "-o", default=".",
        help="Output directory passed to src.main (default: current directory).",
    )
    args = parser.parse_args()

    params = _load_params(args.params_file)
    argv, config_overrides, warnings = build_argv(params)

    if warnings:
        print("Warnings:")
        for w in warnings:
            print(f"  ⚠  {w}")
        print()

    # Resolve the repo root (parent of src/)
    repo_root = Path(__file__).resolve().parent.parent
    config_yaml_path = repo_root / "config.yaml"

    full_cmd = [sys.executable, "-m", "src.main"] + argv + ["--output", args.output]
    print("Command:")
    print(" ", shlex.join(full_cmd))

    if config_overrides:
        yaml_text = _dict_to_yaml(config_overrides)
        print()
        print("config.yaml overrides (written automatically when --run is used):")
        print(yaml_text)

    if not args.run:
        if config_overrides:
            print()
            print(
                "Tip: create config.yaml in the repo root with the content above, "
                "or re-run with --run to have this script manage it automatically."
            )
        return

    # ── Execute ────────────────────────────────────────────────────────────────
    config_yaml_existed = config_yaml_path.exists()
    wrote_config = False
    try:
        if config_overrides:
            if config_yaml_existed:
                print(
                    f"\nWarning: {config_yaml_path} already exists and will not be "
                    "overwritten. Merge the overrides above manually."
                )
            else:
                config_yaml_path.write_text(_dict_to_yaml(config_overrides) + "\n", encoding="utf-8")
                wrote_config = True
                print(f"\nWrote temporary config.yaml to {config_yaml_path}")

        print()
        result = subprocess.run(full_cmd, cwd=str(repo_root))
        sys.exit(result.returncode)
    finally:
        if wrote_config and config_yaml_path.exists():
            config_yaml_path.unlink()
            print(f"Removed temporary config.yaml from {config_yaml_path}")


if __name__ == "__main__":
    main()
